### ISSUE TITLE
Write a documentation explaining how to compile and use locally?

### ISSUE THREAD

**Issue by Naereen** [generative-fm/play#11]
Hello there,
I'm a huge fan and long time user of your awesome website.
I love the new interface! Congrats!

I'm very often working offline, sometimes because I want, mainly because I have to.
I would love to have a [`localhost/generative.fm`](http://localhost/generative.fm) folder on my local webserver, to use generative-fm locally.

When the documentation will be written, could you please explain how to download, compile and run/install locally the project?
A clear bonus could be to offer a .zip archive (in the `release` tab of his GitHub project) containing all the js/css files and a ready-to-work `index.html` file.

Thanks in advance, and good luck :smiley:.

**Comment by alexbainter** [comment]
Hi @Naereen, I will definitely add instructions for running the project offline. That said, I actually built the player to work offline already, so that should be working for you as long as you're using a modern browser and you don't clear your browser's data or something. You can play any generator offline as long as you played it once online, and when you use the service while you're offline, you can see which generators aren't available:

![Screenshot from 2021-02-15 11 19 50](https://user-images.githubusercontent.com/6510436/107977011-0aa4c680-6f80-11eb-83ef-18bc645e49c8.png)
![Screenshot from 2021-02-15 11 20 02](https://user-images.githubusercontent.com/6510436/107977017-0c6e8a00-6f80-11eb-8c0f-10918cc82f00.png)

I'm about to fix a bug where trying to play a generator that isn't available will endlessly spin; otherwise it will display a message that it couldn't be played.

Eventually I'll add a way for you to save generators for offline playback without having to actually play them first, and I'll also be releasing a desktop app at some point in the future.

**Comment by Naereen** [comment]
Whoooo that's awesome!
I had the intuition that the tool could be used offline but I didn't know you wrote such a clean UI for this specific feature!
Never mind my request about installing it locally, honestly this is brilliant!

**Comment by alexbainter** [comment]
That's great to hear this will work for you!

PS, a fix for the endless loading spinner issue I mentioned is in v0.2.4 and on it's way out the door: https://github.com/generative-fm/play/actions/runs/569400537.

**Comment by Naereen** [comment]
Another solution I just discovered is [webcatalog.app](https://webcatalog.app/), and apparently I can set-up a [custom app](https://help.webcatalog.app/article/21-can-i-create-custom-app) using <https://play.generative.fm/browse>

I'll add screenshots or a GIF showing this, just for demonstration.

**Comment by Naereen** [comment]
![Peek 17-02-2021 04-39](https://user-images.githubusercontent.com/11994719/108153105-c8dc6300-70da-11eb-9ffb-0808d44a1109.gif)
